export const HomePageLocators = {
    bannerSection: `//div[@class="owl-carousel imgslider imgslider1 owl-loaded owl-drag"]`,
    imgInsideBanner: `//div[@class="owl-carousel imgslider imgslider1 owl-loaded owl-drag"]//img`,
    categorySection: `//div[@class="thecate"]`,
    trendingSection: `//div[@class="owl-carousel trendcate trendingnew owl-loaded owl-drag"]//div[@class="owl-stage-outer"]`,
    imageInCategorySection: `//div[@class="tren-bg"]//div[@class="test"]`,
    textInsideCategorySection: `//div[@class="tren-bg"]//div[@class="test"]//h2`,
    selectedRadioButton: `//input[@checked="checked"]/parent::div//label`,
    otpText: `//div[@class='bodytext ']`,
    otpInputField: `//div[@class='otp-warpper']//input`,
    validateAndLoginButton: `//button[@class='login-button logindown userorlogin ']`,
    enterUserID: `//input[@id="username"]`,
    enterUserPass: `//input[@id="password"]`,
    enterLoginBTN: `//button[@onclick="login()"]`,
    DialogBox: `//dialog[@aria-describedby="tour_step_0-description"]`,
    skipButtonInsideDialogBox: `//button[text()="Skip"]`,
    giftcardoption: "(//a[text()='Gift Cards'])[1]",
    exploreGiftCardTitle: "//div[@class='col-xl-12 col-sm-12 col-12 mt-3']",
    giftCardVisibleIndicator: "//span[@class='showing mb-2 showingblock']",
    giftCardTitle: "//p[@class='card-gift']//a",
    earnPointsBadge: "//a[@class=a'prodiscounternewdesign3 ']",
    giftCardSectionCards: "//div[@class='col-xl-3 col-sm-4 col-6 mb-4 cstmpd ']",
    pointsAndCashText: "//p[@class='start-point']",

};
