export const FlightPageLocators = {
  flightTab: `//a[@id="flights_link"]`,
  onewaybox: `(//label[contains(@class,"wament hand-cursor")])[1]`,
  roundtripbox: `(//label[contains(@class,"wament hand-cursor")])[2]`,
  fromCity: `(//input[@name='from'])[1]`,
  fromCityDropdown: `//ul[@id="ui-id-1"]`,
  firstSearchResultfromCityDropdown: `(//li[@class="custom-auto-complete ui-menu-item"])[1]`,
  toCity: `(//input[@name="to"])[1]`,
  toCityDropdown: `//ul[@id="ui-id-2"]`,
  firstSearchResulttoCityDropdown: `(//ul[@id="ui-id-2"]//li[@class="custom-auto-complete ui-menu-item"])[1]`,
  departureDate: `//input[@id="flight_datepicker1"]`,
  returnDate: `//input[@id="flight_datepicker2"]`,
  currentMonth: `//span[@class='ui-datepicker-month']`,
  currentYear: `//span[@class='ui-datepicker-year']`,
  nextMonthButton: `//a[@data-handler='next']`,
  fareSummaryDropdown: `//ul[@class='text-list']`,
  hotelName: `(//div[@class='hotel_info']//h5)[1]`,
  prevButton: `//a[@title='Prev']`,
  dateCell: (day: string) => `//td[@data-handler='selectDay']//a[text()='${day}']`,
  VerifyOneWayRoundTripCalendar: `//div[@id="fare_calendar_wrapper"]`,
  FlightRoundTripDetailsBox: `//li[contains(@class,"domestic_round_segment")] | //div[contains(@id,"_trip_header")]`,
  travellersAndCabinClass: `//div[contains(@class,'mainSearchbox')]`,
  roomCountDropdown: `//div[contains(@class,"roomcountMob")] `,
  travellersAdultPlusButton: `//div[contains(@class,"adult_count_div")]//button[@data-type="plus"]`,
  travellersAdultMinusButton: `//div[contains(@class,"adult_count_div")]//button[@data-type="minus"]`,
  travellersChildrenPlusButton: `//div[contains(@class,"child_count_div")]//button[@data-type="plus"]`,
  travellersInfantPlusButton: `//div[contains(@class,"infant_count_div")]//button[@data-type="plus"]`,
  travellersApplyButton: `//a[text()="Apply"] | //div[@class="inallsn"]//a[text()="Done"]`,
  travellerCount: `//span[@class='total_pax_count']`,
  travelsummaryCount: `//div[@class="travell_info"]`,
  travelClassEconomyOption: `//a[text()="Economy"]`,
  travelClassPremiumEconomyOption: `//a[text()="Premium Economy"]`,
  travelClassText: `//span[@id="travelClass"]`,
  nonStopCheckbox: `//label[text()="Non-stop"]`,
  searchFlightsButton: `//input[@id="flight-form-submit"]`,
  firstRecentSearch: `//div[@id="ga_search_view_flight_0"]`,
  travelDetailsField: `//div[@id="onw_rndw_fieldset"]`,
  phoneCopyButton: `//div[@class="calldatabox"]//span[@class="phone_copy"]`,
  emailCopyButton: `//div[@class="calldatabox"]//span[@class="email_copy"]`,
  firstFlightCard: `(//div[contains(@class,'flight') and contains(@class,'Card')])[1]`,
  FligthStopDetails: `(//div[contains(@class,"stoDet stop")])[1]`,
  FlightRefundableText: `(//span[@class="_refundable"])[1] | (//div[text()="Refundable"])[1]`,
  FlightNonRefundableText: `(//span[@class="_nonrefundable"])[1]`,
  FlightAirlineName: `(//h4[@class="_airline_name"])[1] | (//div[contains(@class,"airlinename")])[1]`,
  filterErrorMessage: `//div[@id="fliter_error_box"]`,
  flightListFilterButton: `//span[text()="Sort & Filter"]`,
  filterTabStops: `(//a[text()="Stops "])[1] | //button[contains(text(),"Stops")]`,
  filterTabDepartureTime: `(//a[text()="Departure "])[1] | //button[contains(text(),"Departure Time")]`,
  filterTabArrivalTime: `(//a[text()="Arrival "])[1] | //button[contains(text(),"Arrival Time")]`,
  filterTabFareType: `(//a[text()="Fare type "])[1]`,
  filterTabAirlines: `(//a[text()="Airline "])[1] | //button[contains(text(),"Airlines")]`,
  filterTabLayoverAirports: `(//a[text()="Layover Airports "])[1]`,
  filterApplyButton: `(//button[text()="Apply"])[1]`,
  filterClearButton: `(//button[text()="Clear All"])[1]`,
  filterNonStop: `(//div[@class="filterboxcontent"]//label[text()="Non-stop"])[1] | (//div[@class="stopbig"])[1]`,
  filter1Stop: `(//div[@class="filterboxcontent"]//label[text()="1 Stop"])[1] | (//div[@class="stopbig"])[2]`,
  filter1PlusStop: `(//div[@class="filterboxcontent"]//label[text()="1+ Stops"])[1]`,
  filterNonStopReturn: `(//div[@class="filterboxcontent stops_return"]//label[text()="Non-stop"])[1]`,
  filter1StopReturn: `(//div[@class="filterboxcontent stops_return"]//label[text()="1 Stop"])[1]`,
  filter1PlusStopReturn: `(//div[@class="filterboxcontent stops_return"]//label[text()="1+ Stops"])[1]`,
  filterDepartureTimeEarlyMorning: `(//div[@class="filterboxcontent"]//label[text()="Early Morning"])[1] | //div[@id="departureTimeWrapper"]//div[@class="starin"]//span[text()="12-6AM"]`,
  filterDepartureTimeMorning: `(//div[@class="filterboxcontent"]//label[text()="Morning"])[1] | //div[@id="departureTimeWrapper"]//div[@class="starin"]//span[text()="6-12PM"]`,
  filterDepartureTimeAfternoon: `(//div[@class="filterboxcontent"]//label[text()="Afternoon"])[1] | //div[@id="departureTimeWrapper"]//div[@class="starin"]//span[text()="12-6PM"]`,
  filterDepartureTimeEvening: `(//div[@class="filterboxcontent"]//label[text()="Evening"])[1] | //div[@id="departureTimeWrapper"]//div[@class="starin"]//span[text()="6-12AM"]`,
  FilterDepartureTimeEarlyMorningReturn: `(//div[@class="filterboxcontent departure_return"]//label[text()="Early Morning"])[1]`,
  FilterDepartureTimeMorningReturn: `(//div[@class="filterboxcontent departure_return"]//label[text()="Morning"])[1]`,
  FilterDepartureTimeAfternoonReturn: `(//div[@class="filterboxcontent departure_return"]//label[text()="Afternoon"])[1]`,
  FilterDepartureTimeEveningReturn: `(//div[@class="filterboxcontent departure_return"]//label[text()="Evening"])[1]`,
  filterArrivalTimeEarlyMorning: `(//div[@class="filterboxcontent"]//label[text()="Early Morning"])[2] | //div[@id="arrivalTimeWrapper"]//div[@class="starin"]//span[text()="12-6AM"]`,
  filterArrivalTimeMorning: `(//div[@class="filterboxcontent"]//label[text()="Morning"])[2] | //div[@id="arrivalTimeWrapper"]//div[@class="starin"]//span[text()="6-12PM"]`,
  filterArrivalTimeAfternoon: `(//div[@class="filterboxcontent"]//label[text()="Afternoon"])[2] | //div[@id="arrivalTimeWrapper"]//div[@class="starin"]//span[text()="12-6PM"]`,
  filterArrivalTimeEvening: `(//div[@class="filterboxcontent"]//label[text()="Evening"])[2] | //div[@id="arrivalTimeWrapper"]//div[@class="starin"]//span[text()="6-12AM"]`,
  FilterArrivalTimeEarlyMorningReturn: `(//div[@class="filterboxcontent arrival_return"]//label[text()="Early Morning"])[1]`,
  FilterArrivalTimeMorningReturn: `(//div[@class="filterboxcontent arrival_return"]//label[text()="Morning"])[1]`,
  FilterArrivalTimeAfternoonReturn: `(//div[@class="filterboxcontent arrival_return"]//label[text()="Afternoon"])[1]`,
  FilterArrivalTimeEveningReturn: `(//div[@class="filterboxcontent arrival_return"]//label[text()="Evening"])[1]`,
  filterTabFareTypeRefundable: `(//label[text()="Refundable"])[1]`,
  filterTabFareTypeNonRefundable: `(//label[text()="Non-Refundable"])[1]`,
  FilterAirlinesFirstFlight: `(//div[@class="airline_filter_class"]//div[@class="inputselct"]//label[@class="lbllbl"])[1]`,
  FilterAirlinesFirstFlightCheckbox: `(//div[@class="airline_filter_class"]//div[@class="inputselct"]//label)[1]`,
  filterFirstAirlineInList: `(//div[@class="airline_filter_class"]//label)[2] | (//div[@id="allairlines"]//li//label)[2]`,
  filterFirstAirlineCheckboxInList: `(//div[@class="airline_filter_class"]//label)[1] | (//div[@id="allairlines"]//li//label)[1]`,
  nextButtonOnFlightDetailsPage: `//button[text()="Next"]`,
  airlinenameOnFlightDetailsPage: `(//div[@class='a-n airlinename'])[1]`,
  bookNowButtonOnFlightDetailsPage: `(//div[@id="flight_search_result"]//button[text()="Book Now"])[2]`,
  bookButtonOnFairDetailsPage: `//div[@class="trip_body trip0  "]//button[text()="Book"] | (//div[@class="flightInforMain"]//a[contains(text(),"Book Now")])[1]`,
  continueButtonOnFlightDetailsPage: `//button[@id="move_to_pax_details_section"] | //button[@class="bookcont contin_servc_btn"]`,
  addnewTravellerButton: `//button[@class="add_new_btn"]`,
  travellerGenderMR: `//label[text()="Mr."]`,
  FirstNameErrorMessage: `//p[text()="Please enter a valid first name"] | //i[contains(text(),"Please enter a valid first & middle name")]`,
  LastNameErrorMessage: `//p[text()="Please enter a valid last name"] | //i[contains(text(),"Please enter a valid last name")]`,
  firstNameInput: `//input[contains(@class,"first_name_input")] | //input[contains(@id,"passenger-first-name-1")]`,
  lastNameInput: `//input[contains(@class,"last_name_input")] | //input[contains(@id,"passenger-last-name-1")]`,
  FirstTravellerNameOnSummary: `(//div[@class="flduserbox"])[2] | (//td[@class="seat_pax_name"])[1]`,
  addTravellerButton: `//span[text()="Add Traveller"]`,
  FirstTravellerNameEditButton: `(//button[@class="fld_travel_edit"])[1]`,
  FirstOptionCheckbox: `//div[@class="inputcheckbox"]//label[@for="pax401"]`,
  firstTravellerNameEditConfirmButton: `//span[text()="Confirm"]`,
  travellerEmail: `//h5[text()="Email"]`,
  travellerPhoneNumber: `//h5[text()="Phone"]`,
  defaultTavellerEmail: `//input[contains(@class,"email_text_input")] | //input[contains(@id,"billing-email")]`,
  defaultTravellerPhone: `//input[contains(@class,"phone_text_text")] | //input[contains(@id,"passenger-contact")]`,
  emailErrorMessage: `//p[text()="Email is required"] | //i[text()="* Please enter passenger’s email id"]`,
  phoneErrorMessage: `//p[text()="Phone number is required"] | //i[text()="* Please enter passenger’s mobile number"]`,
  GSTHeader: `//h4[text()="GST Information (Optional)"] | //h4[text()="GST Information"]`,
  defaultGSTNumber: `//input[contains(@class,"booking_gst_number")]`,
  gstErrorMessage: `//p[text()="Please enter a valid GST number"]`,
  passportDetailHeading: `//h4[text()="Passport information"] | //span[text()="Passport Number "]`,
  passportErrorMessage: `//i[text()="* Please enter passenger’s passport number"]`,
  passportCountryErrorMessage: `//i[text()="* Please enter passport’s issuing country"]`,
  passportExpiryErrorMessage: `//i[text()="* Please select passport’s expiry date"]`,
  defaultPassportNumber: `//input[contains(@class,"passport_number_input")] | //input[contains(@id,"passenger_passport_number_1")] `,
  defualtpassportCountry: `//select[contains(@class,"passport_issuing_country_input")] | //select[contains(@id,"passenger_passport_issuing_country_1")]`,
  expireDate: `//input[contains(@class,"expiry_datepicker ")]`,
  passportDay: `//select[@id="passenger_passport_expiry_day_1"]`,
  passportMonth: `//select[@id="passenger_passport_expiry_month_1"]`,
  passportYear: `//select[@id="passenger_passport_expiry_year_1"]`,
  saveTravellInfo: `//label[text()="Save traveller info"]`,
  flightTabFooter: `//a[@id="flights_link_footer"]`,
  hotelTabFooter: `//a[@id="hotels_link_footer"]`,
  contactUsFooter: `//div[@class="frtbest"]//a[contains(text(),"Contact")]`,
  aboutUsFooter: `//div[@class="frtbest"]//a[contains(text(),"About us")]`,
  refundPolicyFooter: `//div[@class="frtbest"]//a[contains(text(),"Refund Policy")]`,
  termsAndConditionsFooter: `//div[@class="frtbest"]//a[contains(text(),"Terms & Conditions")]`,
  privacyPolicyFooter: `//div[@class="frtbest"]//a[contains(text(),"Privacy Policy")]`,
  bookingStatus: `//h4[@class='confm_txt']`,
  confirmedVoucher: `//p[@class='earn']//span`,
  bookingId: `//span[@id='copy_ref']`,
  bookingDate: `//div[@class='travell_info']//p`,
  flightDropdown: `//div[@class='cnf_flt_top']`,
  flightName: `(//div[@class='fltcod'])[1]`,
  departureCity: `(//p[@class='flt_cityname'])[1]`,
  arrivalCity: `(//p[@class='flt_cityname'])[2]`,
  departureTime: `(//p[@class='flt_time'])[1]`,
  arrivalTime: `(//p[@class='flt_time'])[2]`,
  hotelAddress: `(//p[@class='card-text'])[1]`,
  fareSummarySection: `//div[contains(@class,'expand-box')] | //div[contains(@id,"collapseExample")]`,
  fareSummaryItems: `//ul[@class='text-list']//li`,
  topHotelsSection: `//div[@class='card_hed']`,
  topHotelCards: `(//div[@class='owl-item active'])[1]`,
  hotelRedirectLink: `//ul[@class='star']`,
  FlightFromNameShotform: `(//div[contains(@class,'flight') and contains(@class,'Card')])[1]//*[contains(text(),"NMI")] | (//div[contains(@class,'flight') and contains(@class,'Card')])[1]//*[contains(text(),"BOM")] `,
  FlightToNameShotForm: `(//div[contains(@class,'flight') and contains(@class,'Card')])[1]//*[contains(text(),"BLR")] | (//div[text()="(BLR)"])[1]`,
  FlightTOInternationalName: `//h4[text()="DXB"] | (//div[text()="(DXB)"])[1] `,
  FirstTravellerCheckbox: `(//div[@class="inputcheckbox"])[1]`,
  travellerDetailsPageContinuebutton: `//button[@class="flbookbtn traveller_details_continue"]`,
  seatSelectionOption: '//li[@class="seat_li active"]',
  baggageSelectionOption: '//li[@class="baggage_li"]',
  seatMapContainer: '(//div[@class="seatselaction_innerbox"])[1]',
  availableSeat: '(//div[@class="columninnebox extrapayhigh"])[1]',
  UnavailableSeat: '(//div[@class="columninnebox Unavailable"])[1]',
  unvailableSeatErrorMessage: `(//p[text()="Sorry! This seat is taken"])[1]`,
  seatPrice: `(//h4[contains(@class,'fl_det_footer') and contains(text(),'₹')])[3]`,
  weightIncreasePlusButton: `//h3[text()="5 KG"]/parent::div/following-sibling::div//span[@class="coplus"]`,
  skipAndPayButton: '//a[@class="skipbtn skipToCheckout"]',
  travellerAndAddoneHeading: `//h4[text()="Travellers & Add-ons"]`,
  travellersAndAddonsContinueButton: `//button[@class="bookcont continue_redm_button poptimemsg"] | //button[@class="flbookbtn extra_service_cont_btn"]`,
  noFlightsText: `//h5[@class="no_flts"]`,
  fromCityMobile: `//input[@id="from" and @placeholder="Select city or airport"]`,
  fromCitySearchMobile: `(//input[@id="from" and @placeholder="Search for city or airport"])[2]`,
  cityDropDownMobile: `(//ul[@id="airport_list"]//div)[1]`,
  firstSearchResultCityDropDownMobile: `(//ul[@id="airport_list"]//div)[1]`,
  toCitySearchMobile: `(//input[@id="to" and @placeholder="Search for city or airport"])[2]`,
  departureDateMobile: `//input[@id="flight_datepicker11_vis"]`,
  returnDateMobile: `//input[@id="flight_datepicker22_vis"]`,
  dateCellMobile: (date: string) => `(//div[@class="day-cell"][@data-date="${date}"])[1]`,
  departureInputMobile: `(//input[@placeholder="Select a date" and @name="depature"])[2]`,
  returnInputMobile: `(//input[@placeholder="Select a date" and @name="return"])[2]`,
  doneCalendarButtonMobile: `//button[@id="clendr-btn"]`,
  closeTravellerAndCabinButtonMobile: `(//span[text()="×"]/parent::button)[1]`,
  filterIconMobile: `//a[@class="filterbtn"]`,
  passengerAlert: `//small[text()="Max 9 Passenger(Adult+Child) Allowed"] | //span[text()="Max 9 passengers (Adult+Child) allowed"]`,
  passnagermobile: `//input[@name='passenger_contact']`,
  doneTravellerAndCabinButtonMobile: `//a[@class="done1 comnbtn_room1"]`,
  filterButtonMobileForBOB: `//li[@class="sortli filt_mob filter_tab"]`,
  exprieYear: `//select[@class="ui-datepicker-year"]`,
  reviewtravllerbutton: `(//button[@class='confirm_traveller_btn add_fav'])[2]`,
  

};
