export const PaymentPageLocators = {
  checkoutPayButton: `//small[@id='amount-impression']`,
  proceedButton: `//button[@class="common-btn" and normalize-space()="PROCEED"]`,
  backIconButton: `//i[@class='back-btn']`,
  confirmBackButton: `//button[@class="common-btn txt-btn"]`,
  cardOptionSelector: `//div[@class='boxedPaymentOptions']//ul//li | (//div[@class='text-base empty:hidden'])[1]`,
  debitcreditcardOption: `//div[@class='boxedPaymentOptions']//ul//li[1]`,
  cardNumberField: `//input[@id='cardNumber'] | //input[@name='card.number']`,
  cardExpiryField: `//input[@id='cardExpiry'] | //input[@name='card.expiry']`,
  cardCvvField: `//input[@id='cardCvv'] | //input[@name='card.cvv']`,
  cardownername: `//input[@id='cardOwnerName']`,
  payotp:`//input[@id='password']`,
  saveCardPopup: `//input[@id='userConsentCheckbox'] | //input[@data-testid='save-card-checkbox']`,
  withoutSavingCardOption: `//label[@for='withoutSavingCard']`,
  closeWithoutSaveButton: `//button[@data-testid="closeWithoutSave"]`,
  savecardbob: `//input[@data-testid='save-card-checkbox']`,
  canceltext: `//h3[text()='Cancel Payment']`,
  cancelButton: `//button[@data-testid='submit']`,
  nocancelbutton: `//button[@data-testid='cancel']`,
  otpInputField: `//input[@id="password"]`,
  paybutton:`//input[@id='submitBtn']`,
  bookingConfirmationPage: `//h4[text()='Booking Confirmed']`,
  bookingPendingPage: `//h4[text()='Booking Pending']`,
  bookingreferenceNumber: `//p[@class='book_ref_no']`,
  invalidOtpError:`//p[@id='OTPStatus']`,
  otpErrorMessage: `//span[contains(@class,'error')]`,
  submitButton: `//input[@id='submitBtn']`,
  backIconButtonMobile: `//i[@class='back-btn']`,
  payNowButtonBob: `//a[@id='pay_btn_new']`,
  termsConditionCheckboxBob: `//label[@for='terms_cond1']`,
  continueTravellerButtonBob: `//button[@id='redeem_pt_new']`,
  continueButtonBob: `(//button[contains(@class,'btn-primary')])[1]`,
  continuebtn: `(//button[@class='btn btn-primarycontinue'])[1]`,
  continueButtonPaymentBob: `//button[@name='button']`,
  otpInputFieldBob: `//input[@name='otp']`,
  finalPaymentButtonBob: `//button[@name='button']`

};
