export const PaymentPageLocators = {
  checkoutPayButton: `//small[@id='amount-impression']`,
  proceedButton: `//button[@class="common-btn" and normalize-space()="PROCEED"]`,
  backIconButton: `//i[@class='back-btn']`,
  confirmBackButton: `//button[@class="common-btn txt-btn"]`,
  cardOptionSelector: `(//div[@class='l1Item'])[1]`,
  debitcreditcardOption: `//div[@class='boxedPaymentOptions']//ul//li[1]`,
  cardNumberField: "(//input[@id='cardNumber' or @name='card.number'])[1]",
  continuebtn: `//button[@class='flbookbtn extra_service_cont_btn']`,
  cardExpiryField: "(//input[@id='cardExpiry' or @name='card.expiry'])[1]",
  continuebuttonbobpayment: `(//button[@class='btn btn-primarycontinue'])[1]`,
  cardCvvField: "(//input[@id='cardCvv' or @name='card.cvv'])[1]",
  cardownername: `//input[@id='cardOwnerName']`,
  payotp: `//input[@id='password']`,
  saveCardPopup: `//input[@id='userConsentCheckbox'] | //input[@data-testid='save-card-checkbox']`,
  withoutSavingCardOption: `//label[@for='withoutSavingCard']`,
  closeWithoutSaveButton: `//button[@data-testid="closeWithoutSave"]`,
  savecardbob: `//input[@data-testid='save-card-checkbox']`,
  canceltext: `//h3[text()='Cancel Payment']`,
  cancelButton: `//button[@data-testid='submit']`,
  nocancelbutton: `//button[@data-testid='cancel']`,
  otpInputField: `//input[@id="password"]`,
  paybutton: `//input[@id='submitBtn']`,
  bookingConfirmationPage: `//h4[text()='Booking Confirmed']`,
  bookingPendingPage: `//h4[text()='Booking Pending']`,
  bookingreferenceNumber: `//p[@class='book_ref_no']`,
  invalidOtpError: `//p[@id='OTPStatus']`,
  otpErrorMessage: `//span[contains(@class,'error')]`,
  submitButton: `//input[@id='submitBtn']`,
  backIconButtonMobile: `//i[@class='back-btn']`,
  payNowButtonBob: `//a[@id='pay_btn_new']`,
  termsConditionCheckboxBob: `//label[@for='terms_cond1']`,
  continueTravellerButtonBob: `//button[@id='redeem_pt_new']`,
  continueButtonBob: `(//button[contains(@class,'btn-primary')])[1]`,
  continuebtnbeforepayment: `(//button[@class='btn btn-primarycontinue'])[1]`,
  continueButtonPaymentBob: `//button[@name='button']`,
  otpInputFieldBob: `//input[@name='otp']`,
  finalPaymentButtonBob: `//button[@name='button']`,
  pointsSlider: `//span[@class="switchslider"]`,
  payOfPointPOPUP: `//div[@class="modal-content redemption-limit"]`,
  usePoint: `//input[@id="currentValue"]`,
  payButton: `//button[@id="rzp-payment-button"]`,
  promoCodeInput: `//input[@id="code"]`,
  promoCodeApplyButton: `//input[@id="apply"]`,
  invalidMessage: `//p[text()="Invalid promo code!"]`,
  mobileNoField: `(//span[@class='relative z-[5] ml-auto flex cursor-text items-center'])[3]`,
  mobileinput: `(//span[@class='relative z-[5] ml-auto flex cursor-text items-center'])[1]`,
  continuebtnformobile: `//button[@name='button']`,
  payviacard: `//div[@data-testid='card']`
};
