export const PaymentPageLocators = {
  checkoutPayButton: `//small[@id='amount-impression']`,
  proceedButton: `//button[@class="common-btn" and normalize-space()="PROCEED"]`,
  backIconButton: `//i[@class='back-btn']`,
  confirmBackButton: `//button[@class="common-btn txt-btn"]`,
  cardOptionSelector: `(//div[@class='l1Item'])[1]`,
  debitcreditcardOption: `//div[@class='boxedPaymentOptions']//ul//li[1]`,
  cardNumberField: "(//input[@id='cardNumber' or @name='card.number'])[1]",
  continuebtn:`//button[@class='flbookbtn extra_service_cont_btn']`,
  cardExpiryField: "(//input[@id='cardExpiry' or @name='card.expiry'])[1]",
continuebuttonbobpayment:`//button[@class='btn btn-success make-payment-btn'] | (//button[@class='btn btn-primarycontinue'])[2]`,
  cardCvvField: "(//input[@id='cardCvv' or @name='card.cvv'])[1]",
  cardownername: `//input[@id='cardOwnerName']`,
  payotp: `//input[@id='password']`,
  saveCardPopup: `//input[@id='userConsentCheckbox'] | //input[@data-testid='save-card-checkbox']`,
  withoutSavingCardOption: `//label[@for='withoutSavingCard']`,
  closeWithoutSaveButton: `//button[@data-testid="closeWithoutSave"]`,
  savecardbob: `//input[@data-testid='save-card-checkbox']`,
  canceltext: `//h3[text()='Cancel Payment']`,
  cancelButton: `//button[@data-testid='submit']`,
  nocancelbutton: `//button[@data-testid='cancel']`,
  otpInputField: `//input[@id="password"]`,
  paybutton: `//input[@id='submitBtn']`,
 bookingConfirmationPage: `//h4[normalize-space()='Booking Confirmed']`,
  bookingconfirmationpagebob: `//h5[text()='Congratulations!']`,
  bookingPendingPage: `//h4[text()='Booking Pending']`,
  bookingpendingPagebob: `//li[@class='process']//strong`,
  bookingreferenceNumber: `//p[@class='book_ref_no']`,
  invalidOtpError: `//p[@id='OTPStatus']`,
  otpErrorMessage: `//span[contains(@class,'error')]`,
  submitButton: `//input[@id='submitBtn']`,
  backIconButtonMobile: `//i[@class='back-btn']`,
  payNowButtonBob: `//a[@id='pay_btn_new'] | //button[@id='mobile_pay']`,
 termsConditionCheckboxBob: `(//label[@for='terms_cond1'] | //input[contains(@class,'termscheck')])[1]`,
  continueTravellerButtonBob: `//button[@id='redeem_pt_new']`,
  continueButtonBob: `(//button[contains(@class,'btn-primary')])[1]`,
  continuebtnbeforepayment: `(//button[@class='btn btn-primarycontinue'])[1]`,
  continueButtonPaymentBob: `//button[@name='button']`,
  otpInputFieldBob: `//input[@name='otp']`,
  finalPaymentButtonBob: `//button[@name='button']`,
  pointsSlider: `//span[@class="switchslider"]`,
  payOfPointPOPUP: `//div[@class="modal-content redemption-limit"]`,
  usePoint: `//input[@id="currentValue"]`,
  payButton: `//button[@id="rzp-payment-button"]`,
  paybuttonbob: `//button[@id='mobile_pay']`,
  promoCodeInput: `//input[@id="code"]`,
  promoCodeApplyButton: `//input[@id="apply"]`,
  invalidMessage: `//p[text()="Invalid promo code!"]`,
  mobileNoField: `(//input[@name="contact"])[2]`,
  mobileinput: `//div[contains(@class,"relative flex flex-col d:grow-0  ")]//input[@name="contact"]`,
  continuebtnformobile: `//button[@name='button']`,
  payviacard: `//div[@data-testid='card']`,
  continueButton: `//button[contains(text(),'Continue')]`,
  maybeLaterButton: `//button[text()="Maybe later"]`,
  successButton: `//button[text()="Success"]`,
  okButton: `//a[text()="OK"]`,
  contactmobileno:`//button[@data-testid='contact-sidebar-widget']`,
  mobileNoInput: `(//span[@class='relative z-[5] ml-auto flex cursor-text items-center'])[3]`,
 termsAndConditionsCheckbox: `//label[@for='terms_cond1']`,
alternateTermsCheckbox: `//input[contains(@class,'termscheck')]`,
makePaymentButton: `//button[@class='btn btn-success make-payment-btn']`,
paymentContinueButton: `(//button[@class='btn btn-primarycontinue'])[2]`,
confirmationContinueButton: `(//button[@class='btn btn-primarycontinue'])[1]`,
razorpayCheckoutFrame: `iframe[src*="api.razorpay.com/v1/checkout"]`,
razorpayContactNumberInput: `[data-testid="contactNumber"]`,
continuebtnformobilebob: `//button[@data-testid='bottom-cta-button']`,
razorpayBankVerifyContinue: `xpath=//*[contains(normalize-space(.),'Bank verification needed')]/following::button[normalize-space(.)='Continue'][1]`,
};