export const PaymentPageLocators = {
  checkoutPayButton: `//small[@id='amount-impression']`,
  proceedButton: `//button[@class="common-btn" and normalize-space()="PROCEED"]`,
  backIconButton: `//i[@class='back-btn']`,
  confirmBackButton: `//button[@class="common-btn txt-btn"]`,
  cardOptionSelector: `//div[@class='boxedPaymentOptions']//ul//li`,
  debitcreditcardOption: `//div[@class='boxedPaymentOptions']//ul//li[1]`,
  cardNumberField: `//input[@id='cardNumber']`,
  cardExpiryField: `//input[@id='cardExpiry']`,
  cardCvvField: `//input[@id='cardCvv']`,
  cardownername: `//input[@id='cardOwnerName']`,
  payotp:`//input[@id='password']`,
  saveCardPopup: `//input[@id='userConsentCheckbox']`,
  withoutSavingCardOption: `//label[@for='withoutSavingCard']`,
  closeWithoutSaveButton: `//button[@data-testid="closeWithoutSave"]`,
  canceltext: `//h3[text()='Cancel Payment']`,
  cancelButton: `//button[@data-testid='submit']`,
  nocancelbutton: `//button[@data-testid='cancel']`,
  otpInputField: `//input[@id="password"]`,
  paybutton:`//input[@id='submitBtn']`,
  bookingConfirmationPage: `//h4[text()='Booking Confirmed']`,
  bookingPendingPage: `//h4[text()='Booking Pending']`,
  bookingreferenceNumber: `//p[@class='book_ref_no']`,
  invalidOtpError:`//p[@id='OTPStatus']`,
  otpErrorMessage: `//span[contains(@class,'error')]`,
  submitButton: `//input[@id='submitBtn']`,
  backIconButtonMobile: `//i[@class='back-btn']`,
};
