export const HomePageLocators = {
    bannerSection: `//div[@class="owl-carousel imgslider imgslider1 owl-loaded owl-drag"]`,
    imgInsideBanner: `//div[@class="owl-carousel imgslider imgslider1 owl-loaded owl-drag"]//img`,
    categorySection: `//div[@class="thecate"]`,
    trendingSection: `//div[@class="owl-carousel trendcate trendingnew owl-loaded owl-drag"]//div[@class="owl-stage-outer"]`,
    imageInCategorySection: `//div[@class="tren-bg"]//div[@class="test"]`,
    trendingcategoriesmobile: `(//div[@class='trend-shape']//h2[text()='Mobile and Accessories'])[2]`,
    plppagetitle:`//h5[@class='heading mb-2']`,
    textInsideCategorySection: `//div[@class="tren-bg"]//div[@class="test"]//h2`,
    selectedRadioButton: `//input[@checked="checked"]/parent::div//label`,
    otpText: `//div[@class='bodytext ']`,
    otpInputField: `//div[@class='otp-warpper']//input`,
    validateAndLoginButton: `//button[@class='login-button logindown userorlogin ']`,
    enterUserID: `//input[@id="username"]`,
    enterUserPass: `//input[@id="password"]`,
    enterLoginBTN: `//button[@onclick="login()"]`,
    DialogBox: `//dialog[@aria-describedby="tour_step_0-description"]`,
    skipButtonInsideDialogBox: `//button[text()="Skip"]`,
    giftcardoption: "(//a[text()='Gift Cards'])[1]",
    exploreGiftCardTitle: "//div[@class='col-xl-12 col-sm-12 col-12 mt-3']",
    giftCardVisibleIndicator: "//span[@class='showing mb-2 showingblock']",
    giftCardTitle: "//p[@class='card-gift']//a",
    earnPointsBadge: "//a[@class='prodiscounternewdesign3 ']",
    giftCardSectionCards: "//div[@class='col-xl-3 col-sm-4 col-6 mb-4 cstmpd ']",
    pointsAndCashText: "//p[@class='start-point']",
    productimagegiftcard: "(//a[text()='Barbeque Nation E-Gift Card - Store'])[3]",
    earnMoreExclusiveVisible: `//section[@id="spcl656"]`,
    verifyProductImageDisplayed: `(//section[@id="spcl656"]//div[@class="proimage1"]//img)[6]`,
    verifyAndGetProductTitle: `(//section[@id="spcl656"]//h6//a)[6]`,
    verifyAndGetProductPricing: `(//section[@id="spcl656"]//div[@class="d-bb"]//p)[6]`,
    verifyAndGetEarnPoints: `(//section[@id="spcl656"]//div[@class="prodiscounternewdesign"])[6]`,
    verifyImgDisplayed: `//div[@class="carousel-item active"]//img`,
    getTitleAndCompare: `//div[@class="yigk"]//h1`,
    getPricingAndCompare: `//div[@id="ctl00_ContentPlaceHolder1_repspecialv2_ctl00_sp"]//p`,
    getEarnPointAndCompare: `//div[@id="ctl00_ContentPlaceHolder1_repspecialv2_ctl00_earndiv"]`,
    getTitleAndCompareMobile: `//h1[@class="pro-name heading-desknone"]`,
    getPricingAndCompareMobile: `//div[@id="ctl00_ContentPlaceHolder1_repspecialv2_ctl00_mrp"]//p`,
    bugerMenuMobile: `//div[@id="burger"]`,
    giftCardOptionMobile: `(//li[@class="menu-item menu-dropdown"]//a//img)[2]`,
};
